# eureka:
#   client:
#     registerWithEureka: false

server:
  port: 8069

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: vehiculos
            uri: http://localhost:8063
            predicates:
              - Path=/api/vehiculos/**
          - id: choferes
            uri: http://localhost:8064
            predicates:
              - Path=/api/choferes/**
          - id: repuestos
            uri: http://localhost:8065
            predicates:
              - Path=/api/repuestos/**
          - id: mantenimiento
            uri: http://localhost:8066
            predicates:
              - Path=/api/mantenimiento/**
          - id: parametros
            uri: http://localhost:8067
            predicates:
              - Path=/api/parametros/**
          - id: viajes
            uri: http://localhost:8068
            predicates:
              - Path=/api/**
          - id: infracciones
            uri: http://localhost:8062
            predicates:
              - Path=/api/**